apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ok4i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-ok4i@sha256:6d5116cadcb1139e4e45e73495f366496b9fd7cbcd7fc8d9131ff84459c240e9
        name: my-nodejs
        resources: {}
status: {}
